services:

  frontend:
    build: ./frontend
    ports:
     - "3000:3000"
  backend:
    build: ./backend
    ports:
     - "8000:8000"
    environment:
      MINIO_USER: minioadmin
      MINIO_PASSWORD: miniopassword
      EMBEDDER_URL: http://embedder:5000
    volumes:
     - ./backend:/test
  mongodb:
    image: mongo:4
    ports:
     - "27017:27017"
    volumes:
     - mongodb_data:/data/db	
  redis:
    image: redis:latest
    ports:
     - "6379:6379"
  minio:
    image: minio/minio
    ports:
     - "9000:9000"
     - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
     - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopassword
  qdrant:
    image: qdrant/qdrant
    ports:
     - "6333:6333"
    volumes:
     - qdrant_data:/data/storage
  embedder:
    build: ./embedder
    ports:
     - "5000:5000"
    environment:
      HF_HOME: /models
    volumes:
     - models:/models
     - ./embedder:/test

volumes:
  mongodb_data:
  minio_data:
  qdrant_data:
  models:
